### ISSUE TITLE
Schlage Connect BE469 add to database

### ISSUE THREAD

**Issue by LBegnaud** [openhab/org.openhab.ui.habmin#175]
I created a login but I'm a little outside my realm of knowledge on creating an xml

It looks like this device is pretty close, if not the same as my lock:

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/303

The reason I think it may not be the same is that if I include my lock into the network, it shows up as:

Z-Wave Node 7 (003B:6341:5044:0.0)

Please let me know what other information you need for me to get this model included in the zwave database. 
##

**Comment by raerae1616** [comment]
I have this lock also, and have been searching all day for more information on how to get it working and/or update the database.  It appears to have been included in HABMin as Node 5 in the UI, but a node5.xml file was not created in /var/lib/openhab2/zwave.

I'm happy to help out however I can to get the Schlage FE469NX (Schlage Connect) locks working with OpenHAB.   

Is there any more information or anything I can provide?

**Comment by LBegnaud** [comment]
yea I'm in the same boat as you @raerae1616 

device seems to be included in the zwave network, but no xml is generated and thus no ability to interact with it.

**Comment by raerae1616** [comment]
I hope someone can provide some more insight into the next step soon, as my Locks are a critical part of my Home Automation, and I'd HATE for them to be left out of my OpenHAB setup which is so flexible and powerful.

I'm willing to help out with whatever information or testing is needed.

**Comment by cdjackson** [comment]
We’re working on getting locks into OH1.

**Comment by raerae1616** [comment]
@cdjackson Thanks for the response!

I have found [this thread regarding Schlage Locks](https://community.openhab.org/t/z-wave-schlage-lock-support/2341/225) but wasn't entirely sure if it was only for OH1, or also OH2?

Near the bottom it has a link to what looks like the branch you were referring to for OH1 here at [dbadia-security-mmerge](https://github.com/cdjackson/openhab/tree/dbadia-security-mmerge).

I've been hacking at OH2 for the past 2 weeks, and just discovered that this is a blocker for my setup.  I guess I'll have to downgrade and start over?  I'm happy to pull this branch and help test out... but it'll take me another weekend to try and get OH1 back to where I have OH2 now . . . 

**I knew I should have been conservative and tried OH1 first, Doh!!!**

**Comment by LBegnaud** [comment]
Ha go figure...I could have sworn I read that locks were prioritized for OH2, so I brought up a new install to test with. Not sure why I didn't just try it in my existing OH1 setup...

Thanks for the info cdjackson I'll check it out as well

**Comment by raerae1616** [comment]
Ok, so I spent all night last night installing OH1 on my raspberry Pi and got it all up and running!  The goal was that I can hopefully get the ZWave binding with Security working and potentially help get my Locks (Schlage BE469NX) added to the database and working as discussed in this thread!

BUT, I hit another -- very annoying -- blocker in that process where the iOS App does NOT refresh settings that change using OH1 . . . ?  It's discussed as somethign that [will not be fixed in this thread.](https://community.openhab.org/t/refresh-of-ios-app/3941). Really?

So now my thought is perhaps I can try to use the Z-Wave binding for OH1 via compatibility layer with OH2?  Because OH2 was working very nicely up until this point with the Z-Wave binding.

Any thoughts on issues I may run into using the Z-Wave Binding [from here (dbadia-security-mmerge)](https://github.com/cdjackson/openhab/tree/dbadia-security-mmerge), in OH2 vai compatiblity layer?

**Comment by cdjackson** [comment]
Closing this as it's not related to HABmin. The security classes are included in OH1 and should be in OH2 very soon.
